### ISSUE TITLE
In ESP32-WROOM-32E it seems to be possible to use IO17 for CLK_OUT

### ISSUE THREAD

**Issue by lrodorigo** [Zelmoghazy/esp32-ethernet-lan8720#1]
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf

From the official datasheet it seems that ONLY the IO16 is used for PSRAM connection, and it is possible to use IO17 for EMAC_CLK_OUT_180 even in modules with an external PSRAM, it should be not a problem that is the 180 degrees shifted clock signal.

![image](https://github.com/user-attachments/assets/0ac9da49-5ed7-45ec-b3b1-995e5918272c)

**Comment by Zelmoghazy** [comment]
Interesting , glad I used GPIO17 :)
